# Generated by Django 3.1.2 on 2020-10-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echobot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='user_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
